# Generated by Django 3.1.2 on 2020-11-12 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='token')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('plain_text', models.TextField(verbose_name='plain_text')),
                ('line_types', models.TextField(blank=True, verbose_name='line_types')),
                ('json', models.TextField(blank=True, verbose_name='json')),
            ],
        ),
    ]
